# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-26 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ffdffr_app.models.face_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ffdffr_app.models.face_image.FaceImageUploader(basedir=b'face_images', field=b'image'), verbose_name='face image')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='create time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_face_images', to=settings.AUTH_USER_MODEL, verbose_name=b'user')),
            ],
            options={
                'verbose_name': 'face image',
                'verbose_name_plural': 'face images',
            },
        ),
    ]
