# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-26 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffdffr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_face_images', to=settings.AUTH_USER_MODEL, verbose_name=b'user'),
        ),
    ]
