# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-26 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, verbose_name='oauth2 token')),
                ('endpoint', models.URLField(verbose_name='oauth2 server endpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_oauth2_tokens', to=settings.AUTH_USER_MODEL, verbose_name=b'user')),
            ],
            options={
                'verbose_name': 'oauth2 token',
                'verbose_name_plural': 'oauth2 tokens',
            },
        ),
        migrations.AlterUniqueTogether(
            name='oauth2token',
            unique_together=set([('token', 'endpoint')]),
        ),
    ]
