# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-10 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cas_app', '0002_auto_20190110_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='owner',
        ),
        migrations.AddField(
            model_name='identity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identity',
            name='enable',
            field=models.BooleanField(default=True, help_text='Designates whether the user can use the ak/sk.', verbose_name='enabled'),
        ),
    ]
